[package]
name = "mc-simulations"
version = "0.1.0"
edition = "2024"
description = "Monte Carlo simulations for trading indicators"
repository = "https://github.com/engan/mc-simulations"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
